default_platform(:ios)

platform :ios do
  desc "Run all tests"
  lane :test do
    scan(
      scheme: "PHTrains",
      clean: true,
      skip_testing: "PHTrainsUITests/*"
    )
  end

  desc "Run tests and upload to TestFlight"
  lane :release do
    scan(
      scheme: "PHTrains",
      clean: true,
      skip_testing: "PHTrainsUITests/*"
    )
    build_app(scheme: "PHTrains")
    upload_to_testflight
  end
end