name: CI

on:
  push:
    branches:
      - '**'
      - '!release/**'

  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec fastlane test

  release:
    runs-on: macOS-latest
    if: github.ref == 'refs/heads/release/**'
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run tests and upload to TestFlight
      run: bundle exec fastlane release
