name: CI/CD Pipeline

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --without=documentation

    - name: Run Tests
      run: |
        bundle exec fastlane scan

  build:
    needs: test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --without=documentation

    - name: Build and Upload to TestFlight
      run: |
        bundle exec fastlane build
        bundle exec fastlane pilot upload
